[package]
name = "ungelify"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "2.0.1"
bytesize = "2.0.1"
clap = { version = "4.5.37", features = ["derive"] }
flate2 = { version = "1.1.1", default-features = false, features = ["zlib-rs"] }
globset = "0.4.16"
indexmap = "2.9.0"
